"""Add badge models and user relationship

Revision ID: 8dc493c306c7
Revises: 
Create Date: 2025-10-25 08:10:23.276626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # <-- THIS IS THE FIX. ADD THIS LINE.


# revision identifiers, used by Alembic.
revision: str = '8dc493c306c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('farm', 'latitude',
                existing_type=sa.DOUBLE_PRECISION(precision=53),
                nullable=True)
    op.alter_column('farm', 'longitude',
                existing_type=sa.DOUBLE_PRECISION(precision=53),
                nullable=True)
    op.alter_column('farm', 'size_acres',
                existing_type=sa.DOUBLE_PRECISION(precision=53),
                nullable=True)
    op.add_column('farmactivity', sa.Column('value', sa.Float(), nullable=True))
    # This line below will no longer cause an error
    op.add_column('farmactivity', sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True)) 
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farmactivity', 'unit')
    op.drop_column('farmactivity', 'value')
    op.alter_column('farm', 'size_acres',
                existing_type=sa.DOUBLE_PRECISION(precision=53),
                nullable=False)
    op.alter_column('farm', 'longitude',
                existing_type=sa.DOUBLE_PRECISION(precision=53),
                nullable=False)
    op.alter_column('farm', 'latitude',
                existing_type=sa.DOUBLE_PRECISION(precision=53),
                nullable=False)
    # ### end Alembic commands ###